"""
flow control-:
                           2) Iterative statement
                            --------------------

-> Q Write a program print your name 10 times on console scree ?
-> print("Lalit")

-> This statement are used to execute a piece of code multiple times in our
   program .

   1) using while loop ->

   2) using for loop ->

    loops are those iterative statement which executes a code multiple time .

Types of loop
-------------
1) Entry  control loop -:  for loop , while loop
2) exit control loop -: do while loop (c, c++ ,java)


                         1) While loop
                         ---------------

=>  syntax-:

    while (condition):        -
        statement 1            |
        statement 2            |       <-   It is a body of while loop  or while block
        statement 3            |
        .........             -

->  It checks the condition again and again until it is false.
->  Identation error & syntax errors which comes at compile time it is generated by compiler.
-> jab tak True hai condition tab tak while block execute hota ragega.
-> If condtion get false the loop terminates
   (condition false hote hi while block ke bahr a jayega of next further
    lines ko execute karega.)
-> First interpreter check while condtion & if condition is true. It goes inside
   while loop and executes it's body until after that it again returns to the
   condition and do the same procedure until conditon become false.

Q When to use while loop ?
-> If we want to execute group of statement iteratively until some condition get false,
   then we should go for while loop.

   loop termination -> end of loop
   Iteratation -> every execution of loop .


   ex-:

   var=50
   while (var != 0):
        print("Guido van Rossum")
        var = var-1
   print("loop terminates")

# so here total Iteration ->50 times
# Condtion check -> 51 times

-> So print need's True or False value in condition
   in python  empty list [] , empty tuple () , empty set or dictionary {}
   will  behave as false .




"""
# i=1
# while(i<10):
#     print("hello world")
#     i=i+1;
    
# var=50
# while (var != 0):
#     print("Guido van Rossum")
#     var = var-1
# print("loop terminates")
# # Guess how many time it will check the condition.
# So this program iterates over 50 times & print statement runs 50 times.

# var =0
# while var>=0:
#     print("Hope you are enjoying learning python one of the most versatile lang.")
#     var= var-1

# Guess how many time it will will run print statement .
# So this program exectue or iterate 2 times but print only 1 time.


# a =0
# while a<=0:
#     print(f"So Tomorrow there will not be any class. so enjoy {chr(128512)} ")
#     a= a-1
#  Guess how many time it will will run print statement .
# Infinite times it will iterate and also print .

# while True:
#     print(f"hello himanshu welcome to today's class{chr(128513)}")

#Guess how many time it will will run print statement .  ->  Infinite times

# while False:
#     print("Hello anushka welcome to today's class")

# # Guess how many time it will will run print statement . -> it will print noting
# as we have given false condition .



"""
  Q  Write a program to take input from user and print the number of count till 
     that number ?
  
  Q print number in reverse order .also take input from user .
  
  Q print sum of all the numbers from a given range asked the range from user.
  
  Q print summ of all the even numbers & odd number seprately.
  
  Q
"""

# a= 10
#  output -: 1 2 3 4 5 6 7 8 9 10

# k = int(input(" Enter a number : "))
# i = 1
# while ( i<=k):
#     print(i,end=" ")
#     i=i+1;

# input : 10 ,  output : 10 9 8 7 6 5 4 3 2 1

# k = int(input(" Enter a number : "))  #10
#
# while ( k>=1):
#     print(k,end=" ")
#     k=k-1;

# for i in range(12,0,-1):
#     print(i)


# k = int(input(" Enter a number : "))  #5
# sum=0
# while ( k>=1):
#     sum=sum+k
#     print(sum)
#     k=k-1;
# print("Total sum= ",sum)

# k = int(input(" Enter a number : "))    # 10
# even=0
# odd=0
# while ( k>=1):
#     if (k%2==0):
#         even=even+k
#     else:
#         odd = odd+k
#     k=k-1;
# print("even sum= ",even)
# print("odd sum= ",odd)


# num = 128512
# for i in range(128600):
#     print(chr(i) , end=" ")


